[webhooks]
  url = "http://localhost:3000/api/stripe/webhook"
  events = [
    "checkout.session.completed",
    "customer.subscription.created",
    "customer.subscription.updated",
    "customer.subscription.deleted",
    "invoice.payment_succeeded"
  ] 